site_name: Delpro IT - Field Service Application Documentation
site_url: https://delprosoftware.github.io/documentation/
nav:
  - Welcome: index.md
  - Helpdesk:
      - 'Creating Jobs': helpdesk/jobcreate.md
      - 'Editing Jobs': helpdesk/jobedit.md
      - 'Searching Jobs': helpdesk/jobsearch.md
      - 'Clock In/Out': clockinout.md
      override: 'Helpdesk'
  - Technician: 
      - 'Job List': technician/joblist.md
      - 'Job Details': technician/jobdetails.md
      - 'Clock In/Out': clockinout.md
      override: 'Technician'
  - Contractor: contractor.md
  - Accounts: accounts.md
  - Administration: administration.md

{% if nav.tabs == "Helpdesk" %}
## Helpdesk Clock In/Out
{% elif nav.tabs == "Technician" %}
## Technician Clock In/Out
{% endif %}

theme:
  name: material
  logo: img/delpro_it_logo.PNG
  collapse_navigation: false
  features:
    - navigation.instant #Faster navigation
    - navigation.instant.prefetch #Preloads page on hover
    - navigation.instant.progress #Shows loading bar for slowing connections
    - navigation.expand #Shows all navigation options for page
    - navigation.path #Shows relevant site pathing at the top of the page
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: #B3E5FC
      accent: #81D4FA 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: #B3E5FC
      accent: #80CBC4

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "&copy; 2024 Delpro IT"

extra_css:
  - css/styles.css

