name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install mkdocs
      - name: Install mkdocs
        run: pip install mkdocs

      # Optionally, install mkdocs-material or other mkdocs plugins if you use them
      # - run: pip install mkdocs-material

      # Use cache to speed up dependencies installation
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: |
            ~/.cache/pip

      # Configure Git with GitHub Actions bot and deploy with mkdocs
      - name: Configure Git and Deploy with mkdocs
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          mkdocs gh-deploy --force
