name: ci

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Setup Python environment
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install mkdocs
      - name: Install mkdocs
        run: pip install mkdocs

      # Optionally, install mkdocs-material or other mkdocs plugins if you use them
      # - run: pip install mkdocs-material

      # Use cache to speed up dependencies installation
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          path: |
            ~/.cache/pip

      # Deploy with mkdocs
      - name: Deploy with mkdocs
        run: mkdocs gh-deploy --force
